### ISSUE TITLE
Remove subscription prompt in update script for IS 5.9.0

### ISSUE THREAD

**Issue by Savidude** [wso2/ansible-is#36]
**Description:**
The [update script](https://github.com/wso2/ansible-is/blob/master/scripts/update.sh#L115) prompts if the user has a WSO2 subscription and then validates by checking if the in-place tool exists inside the pack.

This validation will serve no purpose in the Identity Server 5.9.0 as the in-place tool is available in the GA pack. Therefore, this prompt should be removed.

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**
@chirangaalwis

**Comment by madurangasiriwardena** [comment]
Closing the issue due to the inactivity of the repository.
