### ISSUE TITLE
Get a specific update by passing the timestamp

### ISSUE THREAD

**Issue by godwinamila** [wso2/ansible-is#42]
**Description:**
There should be a way to pass the wum timestamp to update.sh and get the update

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madurangasiriwardena** [comment]
Closing the issue due to the inactivity of the repository.
